# Generated by Django 2.2.13 on 2021-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference_id', models.CharField(max_length=255)),
                ('s3_bucket_name', models.CharField(choices=[('ipplbapi', 'Devapi S3 Bucket - ipplbapi'), ('ipplbauth', 'Auth S3 Bucket - ipplbauth'), ('ipplbvault', 'Vault S3 Bucket - ipplbvault')], max_length=255)),
                ('datestamp', models.CharField(max_length=255)),
                ('temp_folder', models.CharField(max_length=255)),
            ],
        ),
    ]
