# Generated by Django 2.2.13 on 2021-03-02 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationExtendsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_template_base64', models.TextField()),
                ('fp_bmp_base64', models.TextField()),
                ('fp_encode_wsq', models.TextField()),
                ('fp_image_height', models.CharField(max_length=255)),
                ('fp_image_width', models.CharField(max_length=255)),
                ('fp_image_resolution', models.CharField(max_length=255)),
                ('fp_image_quality', models.CharField(max_length=255)),
                ('fp_image_nfiq', models.CharField(max_length=255)),
                ('fp_image_wsq_size', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
