# Generated by Django 2.2.13 on 2021-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marie', '0003_auto_20210302_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fp_image_height',
            new_name='fp_image_dimension',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fp_image_quality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fp_image_resolution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fp_image_width',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fp_bmp_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fp_encode_wsq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fp_image_nfiq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fp_image_wsq_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
